name: Create Version Tag and Release

on:
  push:
    branches:
      - main  # Adjust this to your branch

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract version from vencord.sh
        id: get_version
        run: |
          VERSION=$(grep 'currentVersion=' windows_vencord.sh | cut -d '"' -f 2)
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Create and Push Tag
        run: |
          TAG="v${VERSION}"
          git tag $TAG
          git push origin $TAG

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows_vencord.sh
            linux_vencord.sh
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
